name: AntiOrphan
version: '${project.version}'
main: su.dice.antiorphan.AntiOrphan
api-version: '1.20'
depend: [CoreProtect]
authors: [erxson]

commands:
  antiorphan-debug:
    description: 'депук'
    permission: antiorphan.debug
  antiorphan-reload:
    description: 'фыв'
    permission: antiorphan.reload